services:
  django:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
  
  postgres:
    image: postgres:15.8-alpine3.20
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_PASSWORD=root
  
  redis:

  rabbitmq: