FROM python:3.12.6-slim

ENV PIPENV_VENV_IN_PROJECT 1

RUN pip install pipenv

RUN useradd -ms /bin/bash my-user

COPY start.sh /app/start.sh

USER my-user

WORKDIR /app

RUN chown -R my-user /app

COPY . .

RUN chmod +x /app/start.sh

RUN pipenv install

CMD ['/app/start.sh']